DROP DATABASE QuanLyBanHang;
CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer(
cID INT PRIMARY KEY AUTO_INCREMENT,
cName VARCHAR(70),
cAge INT
);

CREATE TABLE `Order`(
oID INT PRIMARY KEY AUTO_INCREMENT,
cID INT,
oDate VARCHAR(70),
oTotalPrice DOUBLE,
FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE Product(
pID INT PRIMARY KEY AUTO_INCREMENT,
pName VARCHAR(70),
pPrice DOUBLE
);

CREATE TABLE orderDetail(
oID INT,
pID INT,
odQTY VARCHAR(70),
FOREIGN KEY (oID) REFERENCES `Order`(oID),
FOREIGN KEY (pID) REFERENCES Product(pID)
);